---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      config: .eslintrc
  fixme:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "source/**/*.scss"
  - "**.js"
exclude_paths:
- source/js/lib/jquery-3.1.0.min.js
- Gruntfile.js
