theme: just-the-docs
title: Geocaching Utils
description: ...a free extension for Google Chrome that improves the geocaching.com website.
show_downloads: false
aux_links:
  "Download from Chrome Webstore":
    - "//github.com/pmarsceill/just-the-docs"